
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    level:
        reactor:
            netty: INFO
        org:
            springframework:
                cloud:
                    gateway: INFO

server:
    port: 8765
spring:
    application:
        name: api-gateway
    cloud:
        discovery:
            enabled: true
        gateway:
            httpclient:
                wiretap: true
                httpserver:
                    wiretap: true
            globalcors:
              cors-configurations:
                '[/**]':
                    allowedOrigins:
                      - '*'
                    allowedHeaders: "*"
                    exposedHeaders:
                      - '*'
                    allowedMethods:
                      - GET
                      - POST
                      - OPTIONS
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            metrics:
                enabled: true



    config:
        activate:
            on-profile: dev

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka

---

spring:
    config:
        activate:
            on-profile: aws

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://naming-server:8761/eureka
    instance:
        prefer-ip-address: true

---

spring:
    profiles:
        active: ${PROFILE:dev}



