
server:
    port: 8095
spring:
    application:
        name: component-processing-service
    datasource:
        driverClassName: org.h2.Driver
        password: root
        url: jdbc:h2:mem:devdb;DB_CLOSE_ON_EXIT=FALSE
        username: root
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
        show-sql: true
####################################################
    config:
        activate:
            on-profile: dev

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka

---

spring:
    config:
        activate:
            on-profile: aws

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://naming-server:8761/eureka
    instance:
        prefer-ip-address: true

---

spring:
    profiles:
        active: ${PROFILE:dev}

